[package]
name = "gala"
version = "0.1.0"
authors = ["Michael <localhost>"]

[dependencies]
failure = "0.1"
lazy_static = "1.0"
pest = "1.0"
pest_derive = "1.0"
rustyline = "1.0"
structopt = "0.2"
symbol = "0.1"
