[package]
name = "gala"
version = "0.1.0"
authors = ["Michael Zhang <failed.down@gmail.com>"]
build = "src/build.rs"

[build-dependencies]
lalrpop = "0.16"

[dependencies]
failure = "0.1"
itertools = "0.7"
lalrpop-util = "0.16"
lazy_static = "1.0"
regex = "1.0"
structopt = "0.2"
